# pandas

## Pandas is a Python library.
## Pandas is used to analyze data

In [4]:
import pandas as pd

data=pd.read_csv(r"C:/Users/reshm/OneDrive/Documents/Python Class by besant/PANDAS/student_dataset.csv")


data

,student_id,name,tamil,english,maths,science,socialscience,total,average,grade,Pass / Fail
0,1,Abhay,77.0,66,100.0,51.0,53.0,347,69,D,Pass
1,2,Abhishek,75.0,66,65.0,87.0,99.0,392,78,C,Pass
2,3,Abirami,51.0,52,87.0,73.0,68.0,331,66,D,Pass
3,4,Adhavan,53.0,99,83.0,99.0,79.0,413,83,B,Pass
4,5,Aditya,64.0,82,61.0,93.0,60.0,360,72,C,Pass
...,...,...,...,...,...,...,...,...,...,...,...
295,296,Yuvan,91.0,83,78.0,87.0,86.0,425,85,B,Pass
296,297,Zakir,100.0,64,90.0,80.0,99.0,433,87,B,Pass
297,298,Zara,52.0,73,89.0,75.0,51.0,340,68,D,Pass
298,299,Zeenath,71.0,51,55.0,65.0,71.0,313,63,D,Pass
299,300,Prayarna,85.0,97,51.0,54.0,65.0,352,70,C,Pass

In [3]:
data.head(10)

,student_id,name,tamil,english,maths,science,socialscience,total,average,grade,Pass / Fail
0,1,Abhay,77.0,66,100.0,51.0,53.0,347,69,D,Pass
1,2,Abhishek,75.0,66,65.0,87.0,99.0,392,78,C,Pass
2,3,Abirami,51.0,52,87.0,73.0,68.0,331,66,D,Pass
3,4,Adhavan,53.0,99,83.0,99.0,79.0,413,83,B,Pass
4,5,Aditya,64.0,82,61.0,93.0,60.0,360,72,C,Pass
5,6,Aishwarya,NaN,54,88.0,51.0,55.0,248,50,Incomplete,Pass
6,7,Ajay,55.0,82,53.0,86.0,63.0,339,68,D,Pass
7,8,Akash,86.0,76,89.0,90.0,96.0,437,87,B,Pass
8,9,Akhil,76.0,59,70.0,67.0,80.0,352,70,C,Pass
9,10,Amar,59.0,96,77.0,65.0,53.0,350,70,C,Pass

In [4]:
data.tail()

,student_id,name,tamil,english,maths,science,socialscience,total,average,grade,Pass / Fail
295,296,Yuvan,91.0,83,78.0,87.0,86.0,425,85,B,Pass
296,297,Zakir,100.0,64,90.0,80.0,99.0,433,87,B,Pass
297,298,Zara,52.0,73,89.0,75.0,51.0,340,68,D,Pass
298,299,Zeenath,71.0,51,55.0,65.0,71.0,313,63,D,Pass
299,300,Prayarna,85.0,97,51.0,54.0,65.0,352,70,C,Pass

In [5]:
data.describe()

,student_id,tamil,english,maths,science,socialscience,total,average
count,300.000000,297.000000,300.000000,298.000000,298.000000,299.000000,300.000000,300.000000
mean,150.500000,74.612795,75.343333,74.728188,74.335570,77.277592,374.300000,74.886667
std,86.746758,14.801670,14.773613,15.523739,15.010259,14.602101,37.066829,7.452895
min,1.000000,50.000000,50.000000,31.000000,50.000000,50.000000,248.000000,50.000000
25%,75.750000,61.000000,63.000000,62.000000,60.250000,65.000000,350.000000,70.000000
50%,150.500000,75.000000,75.000000,74.500000,75.000000,77.000000,370.000000,74.000000
75%,225.250000,87.000000,87.000000,88.750000,87.000000,91.000000,400.250000,80.000000
max,300.000000,100.000000,100.000000,100.000000,100.000000,100.000000,485.000000,97.000000

In [6]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   student_id     300 non-null    int64
 1   name           300 non-null    str
 2   tamil          297 non-null    float64
 3   english        300 non-null    int64
 4   maths          298 non-null    float64
 5   science        298 non-null    float64
 6   socialscience  299 non-null    float64
 7   total          300 non-null    int64
 8   average        300 non-null    int64
 9   grade          300 non-null    str
 10  Pass / Fail    300 non-null    str
dtypes: float64(4), int64(4), str(3)
memory usage: 25.9 KB

In [7]:
def add(a,b):
    c=a+b
    return c

k=add(5,7)
print(k)

12

In [7]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()



data["grade"] = label_encoder.fit_transform(data["grade"])
data

,student_id,name,tamil,english,maths,science,socialscience,total,average,grade,Pass / Fail
0,1,Abhay,77.0,66,100.0,51.0,53.0,347,69,3,Pass
1,2,Abhishek,75.0,66,65.0,87.0,99.0,392,78,2,Pass
2,3,Abirami,51.0,52,87.0,73.0,68.0,331,66,3,Pass
3,4,Adhavan,53.0,99,83.0,99.0,79.0,413,83,1,Pass
4,5,Aditya,64.0,82,61.0,93.0,60.0,360,72,2,Pass
...,...,...,...,...,...,...,...,...,...,...,...
295,296,Yuvan,91.0,83,78.0,87.0,86.0,425,85,1,Pass
296,297,Zakir,100.0,64,90.0,80.0,99.0,433,87,1,Pass
297,298,Zara,52.0,73,89.0,75.0,51.0,340,68,3,Pass
298,299,Zeenath,71.0,51,55.0,65.0,71.0,313,63,3,Pass
299,300,Prayarna,85.0,97,51.0,54.0,65.0,352,70,2,Pass

In [8]:
empty_cells = data.isnull()
print(empty_cells)

     student_id   name  tamil  english  maths  science  socialscience  total  \
0         False  False  False    False  False    False          False  False
1         False  False  False    False  False    False          False  False
2         False  False  False    False  False    False          False  False
3         False  False  False    False  False    False          False  False
4         False  False  False    False  False    False          False  False
..          ...    ...    ...      ...    ...      ...            ...    ...
295       False  False  False    False  False    False          False  False
296       False  False  False    False  False    False          False  False
297       False  False  False    False  False    False          False  False
298       False  False  False    False  False    False          False  False
299       False  False  False    False  False    False          False  False

     average  grade  Pass / Fail
0      False  False        False
1      False  False        False
2      False  False        False
3      False  False        False
4      False  False        False
..       ...    ...          ...
295    False  False        False
296    False  False        False
297    False  False        False
298    False  False        False
299    False  False        False

[300 rows x 11 columns]

In [9]:
empty_cells = data.isnull().sum()
print(empty_cells)

student_id       0
name             0
tamil            3
english          0
maths            2
science          2
socialscience    1
total            0
average          0
grade            0
Pass / Fail      0
dtype: int64

In [30]:
#Mean = the average value (the sum of all values divided by number of values). 
#Median = the value in the middle, after you have sorted all values ascending.
#Mode = the value that appears most frequently.

In [6]:
X11=data["tamil"].mean()
X11= round(X11)  # → 75
print(X11)  # 75

75

In [7]:
x1=data["english"].mean()
x1=round(x1)
x1

75

In [8]:
x2=data["maths"].mean()
x2=round(x2)
x2

75

In [10]:
x3=data["socialscience"].mean()
x3=round(x3)
x3

77

In [11]:
x4=data["total"].mean()
x4=round(x4)
x4

374

In [18]:
x6=data["grade"].mode()
x6

0    2
Name: grade, dtype: int64

In [19]:
data["tamil"].fillna(X11,inplace=True)
data["english"].fillna(x1,inplace=True)

C:\Users\reshm\AppData\Local\Temp\ipykernel_11592\3461109067.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  data["tamil"].fillna(X11,inplace=True)
C:\Users\reshm\AppData\Local\Temp\ipykernel_11592\3461109067.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  data["english"].fillna(x1,inplace=True)

0      66
1      66
2      52
3      99
4      82
       ..
295    83
296    64
297    73
298    51
299    97
Name: english, Length: 300, dtype: int64

In [20]:
empty_cells = data.isnull().sum()
print(empty_cells)

student_id       0
name             0
tamil            3
english          0
maths            2
science          2
socialscience    1
total            0
average          0
grade            0
Pass / Fail      0
dtype: int64