In [7]:
import pandas as pd 

data=[1,3,4,5,6]
print(data)
s=pd.Series([data])
#s=pd.Series(data)
s

[1, 3, 4, 5, 6]

0    [1, 3, 4, 5, 6]
dtype: object

import → tells Python to load a library

pandas → a library used for data handling

as pd → gives it a short name (alias)

👉 So later you can write pd.Series() instead of pandas.Series()
-----
data = [1, 3, 4, 5, 6]

You are creating a list

It stores multiple values (numbers here)

👉 data now holds:

[1, 3, 4, 5, 6]
-----
s = pd.Series([data])

This is the important part 👇

pd.Series() → creates a Pandas Series (like a column)

[data] → you are passing a list inside another list

👉 So this becomes:

[[1, 3, 4, 5, 6]]

⚠️ That means:

Pandas treats the entire list as one single element

Not separate rows

👉 Result:

0    [1, 3, 4, 5, 6]
dtype: object
------
Pandas checks:

“What type is each value?”

If values = numbers → int64

If values = text → object

If values = list / mixed → object
-----
Think like this:

1 → number ✅

"hello" → text ✅

[1,2,3] → a box (object) 📦

In [19]:
student={"name":["ram","ragul","krish"],
         "tamil":[90,80,67],
         "english":[22,44,69],
         "maths":[90,89,66]}
print(student["name"])
print(student["tamil"])
print(student["english"][0])
student["science"]=[50,80,58]
student["name"].append("Reshma")
student["tamil"].append(75)
student["english"].append(55)
student["maths"].append(60)
student["science"].append(96)
s=pd.Series(student)
print(s)

['ram', 'ragul', 'krish']
[90, 80, 67]
22
name       [ram, ragul, krish, Reshma]
tamil                 [90, 80, 67, 75]
english               [22, 44, 69, 55]
maths                 [90, 89, 66, 60]
science               [50, 80, 58, 96]
dtype: object

🧠 Step 1: What is student?

👉 This is a dictionary

A dictionary stores data as:

key → value
🔍 Your Dictionary Structure
"name"    → ["ram", "ragul", "krish"]
"tamil"   → [90, 80, 67]
"english" → [22, 44, 69]
"maths"   → [90, 89, 66]

👉 Each key = column name
👉 Each value = list (column data)

🎯 Think Like Excel Table

name	tamil	english	maths

ram	    90	    22	    90

ragul	80	    44	    89

krish	67	    69	    66

👉 Your dictionary is basically table data

🔹 Step 2: What does this line do?
student["name"]

👉 It means:

“Go to dictionary → find key name → give its value”

✅ Output:
["ram", "ragul", "krish"]
🔥 Important Understanding

"name" is a key

["ram", "ragul", "krish"] is the value

So:

student["name"]

👉 returns the entire list

🧠 Internally

Python does:

1. Look inside dictionary
2. Search for key "name"
3. Return its value
-----
⚠️ Important Rule

👉 All lists must be same length

❌ Wrong:

student["name"].append("kumar")  # only name updated

👉 This breaks the table structure

In [21]:
dataframe=pd.DataFrame(student)
dataframe

     name  tamil  english  maths  science
0     ram     90       22     90       50
1   ragul     80       44     89       80
2   krish     67       69     66       58
3  Reshma     75       55     60       96

A DataFrame is a table of data in Python, like an Excel sheet:

Rows → each record (student, product, etc.)

Columns → each feature (name, marks, price, etc.)

It is provided by the Pandas library.

In [22]:
dataframe["name"]

0       ram
1     ragul
2     krish
3    Reshma
Name: name, dtype: str

In [31]:
#Locate Row


print(dataframe.loc[1])#get the row with index label 1

name       ragul
tamil         80
english       44
maths         89
science       80
Name: 1, dtype: object

In [30]:
print(dataframe.loc[[1]])

    name  tamil  english  maths  science
1  ragul     80       44     89       80

| Code                 | Result Type   | Looks Like        | Notes                                                                      |
| -------------------- | ------------- | ----------------- | -------------------------------------------------------------------------- |
| `dataframe.loc[1]`   | **Series**    | 1D (like a list)  | Returns **one row as a Series**, index = column names, values = row values |
| `dataframe.loc[[1]]` | **DataFrame** | 2D (like a table) | Returns **one row as a table** (keeps DataFrame structure)                 |

In [6]:
l=[[1],45]
l[0][0]

1

In [7]:
print(dataframe.loc[[0,1]])

    name  tamil  english  maths
0    ram     90       22     90
1  ragul     80       44     89

In [13]:
import pandas as pd 
student={"name":["ram","ragul","krish"],
         "tamil":[90,80,67],
         "english":[22,44,69],
         "maths":[90,89,66]}



df = pd.DataFrame(student, index = ["stu1", "stu2", "stu3"])

df

       name  tamil  english  maths
stu1    ram     90       22     90
stu2  ragul     80       44     89
stu3  krish     67       69     66

In [14]:
df.loc[["stu1"]]

     name  tamil  english  maths
stu1  ram     90       22     90

In [33]:
# Create a Series
ages = pd.Series([25, 30, 35])

print(ages)

0    25
1    30
2    35
dtype: int64

In [34]:
ages[0]

np.int64(25)

In [35]:

data = {'Name': ['Alice', 'Bob', 'Charlie'], 
        'Age': [25, 30, 35], 
        'Score': [85, 90, 95]}
df = pd.DataFrame(data, index=['a', 'b', 'c'])
print(df)

      Name  Age  Score
a    Alice   25     85
b      Bob   30     90
c  Charlie   35     95

In [36]:
print(df.loc['a'])

Name     Alice
Age         25
Score       85
Name: a, dtype: object

In [37]:
print(df.iloc[0])

Name     Alice
Age         25
Score       85
Name: a, dtype: object

| Aspect        | `loc`                               | `iloc`                    |
| ------------- | ----------------------------------- | ------------------------- |
| Index type    | Label (could be letters, numbers)   | Position (always integer) |
| Range slicing | Inclusive                           | Exclusive                 |
| Supports      | Boolean conditions, lists of labels | Only integers or slices   |

0     1
1     2
2    34
dtype: int64